
env_args:
    # env: 'TicTacToe'
    #env: 'Geister'
    env: 'HungryGeese'
    #env: 'handyrl.envs.parallel_tictactoe'  # specify by path
    source: 'handyrl.envs.kaggle.hungry_geese'

train_args:
    turn_based_training: False
    observation: False
    gamma: 0.8
    forward_steps: 32
    compress_steps: 4
    entropy_regularization: 2.0e-3
    entropy_regularization_decay: 0.3
    update_episodes: 500
    batch_size: 50
    minimum_episodes: 10000
    maximum_episodes: 100000
    epochs: 5000
    num_batchers: 7
    eval_rate: 0.1
    worker:
        num_parallel: 6
    lambda: 0.7
    policy_target: 'TD' # 'UPGO' 'VTRACE' 'TD' 'MC'
    value_target: 'TD' # 'VTRACE' 'TD' 'MC'
    eval:
        opponent: ['random']
    seed: 0
    restart_epoch: 0
    augmentation: True

worker_args:
    server_address: ''
    num_parallel: 8

